# Generated by Django 5.1.6 on 2025-02-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Pass_word', models.CharField(max_length=50)),
                ('Mobile_number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('Date_of_Joining', models.DateField()),
            ],
        ),
    ]
